# Generated by Django 5.1.2 on 2024-11-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
